# -*- coding: utf-8 -*-
# Part of Browseinfo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Bundle Product Pack Advance App',
    'version': '14.0.0.1',
    'category': 'Sales',
    'sequence': 15,
    'summary': 'Advance product bundle pack product kit Print product bundle product pack item product combo product on sale bundle product delivery bundle product pack kit combine product combine product variant print bundle item pack sales bundle delivery pack bundle',
    'description': """ BrowseInfo,
						product_bundle_pack_advance,
						product_bundle_pack,product,
						product Pack,product Bundle,
						product bundle Pack,
						product pack bundle,
						product bundle stock,
						product bundle stock management""",
    'author': 'BrowseInfo',
    'website': 'http://www.browseinfo.in',
    'depends': ['product_bundle_pack','sale'],
    'data': ['views/config_inherit.xml'],
    'demo': [],
    'css': [],
    "price": 24,
    "currency": 'EUR',
    'installable': True,
    'auto_install': False,
    'application': True,
    'live_test_url':'https://youtu.be/XeVjDA83Wpc',
    "images":['static/description/Banner.png'],
}
